---
# Template for large-snapshot component builds (push-only)
# build-images.sh copies this to each component repo and replaces:
#   template-component -> {component_name}
#   large-snapshot-build-template -> large-snapshot-build-{version}
#   COMPONENT_BRANCH_PLACEHOLDER -> component-{component_name} (each component uses its own branch)
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{source_url}}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: "COMPONENT_BRANCH_PLACEHOLDER"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "COMPONENT_BRANCH_PLACEHOLDER"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: large-snapshot-build-template
    appstudio.openshift.io/component: template-component
    pipelines.appstudio.openshift.io/type: build
  name: template-component-on-push
  namespace: dev-release-team-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/template-component:{{revision}}
    - name: dockerfile
      value: Dockerfile
  pipelineSpec:
    description: Large snapshot component build (push-only, multi-arch)
    finally:
      - name: show-sbom
        params:
          - name: IMAGE_URL
            value: $(tasks.build-image-index.results.IMAGE_URL)
        taskRef:
          params:
            - name: name
              value: show-sbom
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:beb0616db051952b4b861dd8c3e00fa1c0eccbd926feddf71194d3bb3ace9ce7
            - name: kind
              value: task
          resolver: bundles
    params:
      - name: git-url
        type: string
      - name: revision
        type: string
      - name: output-image
        type: string
      - name: dockerfile
        type: string
      - default: "false"
        name: build-source-image
        type: string
      - default: "false"
        name: build-image-index
        type: string
    results:
      - name: IMAGE_URL
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    tasks:
      - name: init
        params:
          - name: image-url
            value: $(params.output-image)
          - name: rebuild
            value: "false"
          - name: skip-checks
            value: "false"
        taskRef:
          params:
            - name: name
              value: init
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:b349d24cb896573695802d6913d311640b44675ec082b3ad167721946a6a0a71
            - name: kind
              value: task
          resolver: bundles
      - name: clone-repository
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
          - name: ociStorage
            value: $(params.output-image).git
          - name: ociArtifactExpiresAfter
            value: ""
        runAfter:
          - init
        taskRef:
          params:
            - name: name
              value: git-clone-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:56f65a16d3d0485c64ad85af2c1f3e9b0bb4d02d63f2fd0ebb9498d219ca723d
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(tasks.init.results.build)
            operator: in
            values:
              - "true"
        workspaces:
          - name: basic-auth
            workspace: git-auth
      - name: prefetch-dependencies
        params:
          - name: input
            value: ""
          - name: SOURCE_ARTIFACT
            value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
          - name: ociStorage
            value: $(params.output-image).prefetch
          - name: ociArtifactExpiresAfter
            value: ""
        runAfter:
          - clone-repository
        taskRef:
          params:
            - name: name
              value: prefetch-dependencies-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:36207773434bfad80fc3991d3ccca409d8429dbf5974c4dcd8d54145235b4b7b
            - name: kind
              value: task
          resolver: bundles
        workspaces:
          - name: git-basic-auth
            workspace: git-auth
          - name: netrc
            workspace: netrc
      - name: build-container
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: .
          - name: HERMETIC
            value: "false"
          - name: PREFETCH_INPUT
            value: ""
          - name: IMAGE_EXPIRES_AFTER
            value: ""
          - name: COMMIT_SHA
            value: $(tasks.clone-repository.results.commit)
          - name: BUILD_ARGS
            value: []
          - name: BUILD_ARGS_FILE
            value: ""
          - name: PRIVILEGED_NESTED
            value: "false"
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
          - name: CACHI2_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
        runAfter:
          - prefetch-dependencies
        taskRef:
          params:
            - name: name
              value: buildah-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.7@sha256:7d5818e082e5534cf63946c1a1d380c0ee6b10b5c915340368c9ca081b97c02a
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(tasks.init.results.build)
            operator: in
            values:
              - "true"
      - name: build-image-index
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: COMMIT_SHA
            value: $(tasks.clone-repository.results.commit)
          - name: IMAGE_EXPIRES_AFTER
            value: ""
          - name: ALWAYS_BUILD_INDEX
            value: "true"
          - name: IMAGES
            value:
              - $(tasks.build-container.results.IMAGE_URL)@$(tasks.build-container.results.IMAGE_DIGEST)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: build-image-index
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.2@sha256:985d1efe861b02524a7679ecd855624b3d4e3a2e835b6f8a97ec7d135898ec0b
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(tasks.init.results.build)
            operator: in
            values:
              - "true"
    workspaces:
      - name: git-auth
        optional: true
      - name: netrc
        optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-template-component
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
